---
name: "Quality Check(super-linter)"
# This is the reusable action to run the linter on the repo.
# This works hand in hand with pre-commit

on:
  push:
  workflow_call:

# permissions:
#   contents: read
#   checks: write
#   statuses: write

jobs:
  linter:
    name: "Quality Check(super-linter)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: "Run Super-Linter"
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          DOCKERFILE_HADOLINT_FILE_NAME: .hadolint.yaml
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          VALIDATE_CHECKOV: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          # VALIDATE_PYTHON_RUFF: true
          # VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_MYPY: false
